In [54]:
import pandas as pd
import numpy as np
import numpy.matlib
from numpy import matmul
from numpy import array as matrix, arange, zeros
import sklearn
from sklearn import decomposition

In [45]:
def NMF(V, num_patterns, num_iterations):
    '''
    Args:
        V: numpy.array (n * m)
        num_patterns: int
        num_iterations: int
    
    Returns:
        W: (n * num_patterns)
        H: (num_patterns * m)
        loss: average loss
    '''
    n = V.shape[0]
    m = V.shape[1]
    r = num_patterns
    W = np.random.rand(n, r)
    H = np.random.rand(r, m)
    for it in range(num_iterations):
        print ('iteration on: ', it)
        for i in range(n):
            for j in range(m):
                for k in range(r):
                    W[i][k] *= matmul(V, H.T)[i][k] / matmul(W, matmul(H, H.T))[i][k]
                    H[k][j] *= matmul(W.T, V)[k][j] / matmul(W.T, matmul(W, H))[k][j]
                    
    loss = 0.0
    for i in range(n):
        for j in range(m):
            for k in range(r):
                loss += V[i][j] - W[i][k] * H[k][j]
    
    return W, H, loss

In [46]:
n = 100
m = 100
V = np.random.rand(n, m)
print (V)
W, H, _ = NMF(V, 4, 100)

[[0.07064183 0.43701331 0.62023318 ... 0.8378448  0.86701072 0.63555703]
 [0.35247819 0.84481806 0.41194838 ... 0.52637387 0.46525599 0.23645002]
 [0.7429644  0.00425875 0.22093712 ... 0.04265391 0.97411282 0.75147852]
 ...
 [0.24761179 0.42872662 0.18911479 ... 0.02794577 0.88059206 0.61286395]
 [0.36255831 0.73517021 0.17140004 ... 0.61665731 0.12117218 0.0250612 ]
 [0.86387437 0.26643258 0.42009992 ... 0.80641984 0.98444816 0.31133516]]
iteration on:  0
iteration on:  1
iteration on:  2
iteration on:  3
iteration on:  4
iteration on:  5
iteration on:  6
iteration on:  7
iteration on:  8
iteration on:  9
iteration on:  10
iteration on:  11
iteration on:  12
iteration on:  13
iteration on:  14
iteration on:  15
iteration on:  16
iteration on:  17
iteration on:  18
iteration on:  19
iteration on:  20
iteration on:  21
iteration on:  22
iteration on:  23
iteration on:  24
iteration on:  25
iteration on:  26
iteration on:  27
iteration on:  28
iteration on:  29
iteration on:  30
iteratio

In [51]:
print (_)

15213.870652598722


In [56]:
nmf = decomposition.NMF(n_components=4, max_iter=100)

In [57]:
W1 = nmf.fit_transform(V)
H1 = nmf.components_

In [64]:
A = V - matmul(W, H)
B = V - matmul(W1, H1)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        print (A[i][j], B[i][j])

-0.3590077742138802 -0.3866195356460878
-0.20240028276721533 -0.17665954235013892
0.06446522009379418 0.060671141868708256
0.30997517431938154 0.3028255246488092
-0.17337634267310592 -0.2394041833250024
-0.2900056342831425 -0.29211116967473594
0.4265033202079662 0.4425260037821357
0.10749703761647977 0.11401419879412711
0.32514647244138406 0.3359313680115703
0.41508634352340096 0.4344419492355377
-0.2767381151723729 -0.27399803494414
-0.08889108732400858 -0.10757464606442169
0.28272841129243653 0.29196231063333933
-0.30725638209996464 -0.2951367000119616
-0.40707494349349915 -0.4124652477977211
-0.352813527895558 -0.3634559092684011
-0.025327591645522007 -0.03592053345179136
0.007375332044971539 -0.023686302496708223
-0.3822618706944759 -0.3925795635066918
-0.3433747408658228 -0.3452206935438786
0.39165447921856245 0.39178546543239046
0.47980700323707076 0.47172492781047237
-0.08089386147597116 -0.09746122942816382
0.15940135317370163 0.1701908992950144
-0.005937748879791593 -0.0100903

-0.10527217435459335 -0.11228119211878818
0.41267514748941925 0.4173915383079686
0.14016264520154365 0.14825107226929413
0.025146992225599796 0.006573914819550386
0.19114132511268622 0.19246064102542526
0.3160561528138278 0.3239257342721933
0.09549324083871041 0.08621814601927597
0.31044016230152327 0.29837938658361407
0.22790915579526527 0.23103759652373712
0.07347665719968921 0.08429301058792055
0.017593297004800168 0.02609807356149363
0.3541888261431798 0.3577446956236589
-0.47064801880678764 -0.4801218849995693
-0.2620720811775509 -0.2724919676855748
0.040415104343400676 0.04784777069966617
-0.34620186076015946 -0.3558024677001891
0.25301961088510994 0.25847031731094594
0.0650548213307457 0.04425631276521369
0.39773122652649057 0.3909162915608394
0.27117102490385536 0.27720706537581874
0.45011184778704677 0.4413618348447578
-0.0026273700061578698 0.005160493928216381
0.05735773279873735 0.06394619170347826
-0.1217932576908709 -0.13508472013536132
0.2508789846120947 0.25292802806265

-0.3545255802381437 -0.36502280994347797
0.009308118314079739 0.06297912936996308
-0.007321856508785862 -0.007310642634609732
-0.0804263949857123 -0.07728964488133039
0.5353606517154045 0.5296143236936446
0.4086549183632833 0.44624485171056694
0.44284191513406557 0.4734515252929087
0.020871999597618096 0.04892458548068579
0.2748479030713784 0.25321530094777733
-0.3941860414573346 -0.3997332076997534
0.11425414822942426 0.09627844130770102
0.21533911924453608 0.22171852532034575
0.25465030249061515 0.2311705791106468
0.1506920027704357 0.15806868821860787
0.20274534854762494 0.2381514020975608
-0.30680083236052846 -0.2968254777104258
-0.2904693377779413 -0.26848289529443037
-0.2225866752727088 -0.2143342063259061
-0.11377293824741752 -0.0868229917909985
0.30663860759992617 0.3113250354274438
-0.14161345996775526 -0.1679018451937947
-0.3272078130646958 -0.33479689976846794
0.5822755072178767 0.6074101908250173
0.20714243223173512 0.2288674786654773
0.16979082580529248 0.16537448919981745

-0.07828045787362314 -0.08334194117063776
-0.2314966298713047 -0.23141738570785408
0.4263422880723141 0.42037007425382
0.09339452932846015 0.07648541082051752
-0.5510491288829779 -0.51968427267332
-0.30835821058819823 -0.2975289878543592
-0.17468008787430978 -0.17559527828345833
-0.3574447603375497 -0.3651783477270325
0.042765126837366774 0.03604690464571647
0.09691838676970721 0.087458260290041
-0.18942466252671808 -0.15487885022572945
0.06258191575937755 0.05233807324010925
-0.4193429701554199 -0.4242361189036349
0.002800400802519143 0.019712963954191753
-0.06251758188443024 -0.07512471259605474
0.3445853062838595 0.33808151136127595
0.22702519022911888 0.20376613012272765
0.4720604374578075 0.46179039461558763
0.043178611097810016 0.05666003281951354
0.048874257141742594 0.0328881769285464
0.12350820941666002 0.14003116341805222
-0.3658073716813707 -0.3675991876468656
0.3275273133145298 0.35150365366105896
-0.2715420164884713 -0.2871213566119051
0.40500298981338334 0.401434355048661

0.04138673484365152 0.04746072787184841
0.4873744742788212 0.45818131343228097
0.057612363342419315 0.05065713824131318
-0.3811104429770463 -0.3897372161991455
0.1917919837158496 0.16565305802992314
0.2053015790453494 0.17923545000703578
0.14716891647779712 0.1455193134201226
-0.13757877094103033 -0.13557946591819597
0.07123027181794261 0.07818862379087088
0.3381516651114614 0.32194139092214247
-0.17779294602649287 -0.16252525403112794
0.3276224529011369 0.30857860809006854
-0.07708508943910725 -0.07675668516981604
-0.3472593773080572 -0.33657963000891344
-0.05490711611463578 -0.040874376653267375
-0.26712610170414247 -0.24994080797629775
-0.19131868241989802 -0.1785305253878025
0.4381903711194584 0.4437292135502438
-0.32847587144425805 -0.30465198101589286
-0.29236888118830395 -0.27854089994753317
0.41741135214181957 0.4381611652003807
0.21646137825478584 0.21498628593839264
-0.04266134761538615 -0.046112961057245605
-0.07231068278596092 -0.09616022733390603
-0.29531143479024446 -0.29

0.017057600476125367 0.02530104808236766
0.056332174770193144 0.05865712872289508
0.02580843831497559 0.05519356678659587
0.16492460250339352 0.17069317748673507
0.010317746938751149 -0.010457054001288213
-0.307579214503056 -0.2948874731219845
0.2855677155151536 0.28687067428858154
0.23026876778192662 0.26242139599346953
-0.3106287949007196 -0.28253310759503003
-0.34252305367096536 -0.3436181022856813
0.03511828325465033 -0.007786666584765123
-0.08568300284450092 -0.09687121767675777
-0.30046862822641357 -0.27912649712530424
-0.11529991014306851 -0.13111711177647023
-0.019526544018273473 -0.029897338088707814
0.35243047646514886 0.3682369718383156
0.12689259862683672 0.15380428656551776
0.13349697897945623 0.15655036023038216
0.29732626735566325 0.3325523491581036
-0.10343878293611491 -0.05664738028193522
-0.585817513283938 -0.6074413591273736
-0.4065425602139393 -0.3943084970072856
-0.1934563248660468 -0.224423598022797
-0.31408138169124367 -0.29197549395667904
0.1478295181052654 0.15

0.046673922837902615 0.053145121028487896
0.14003657201846376 0.13024424720655015
-0.40603808430801597 -0.4138152351868772
0.14722121502635643 0.14914084927292548
-0.25397354454793497 -0.24898808972219577
-0.17763706695091297 -0.17357931014297923
-0.18429112600686853 -0.20283972819222884
-0.02137693391868395 -0.030473186309371847
-0.10018876924208076 -0.10273670042754035
0.028789819318399967 0.016922282172296244
0.09941316132545364 0.11454800249056585
-0.1143083451857615 -0.10127877285466635
-0.31849645614840527 -0.33135391665965463
-0.1519340118830106 -0.13851534553388523
0.35235473182616117 0.3598203860524479
-0.04227163229305059 -0.036360187482209205
0.3465249718400034 0.328636841097417
-0.4873102413490521 -0.4818680299051661
0.2508428130200939 0.28203804443104685
0.36214341654806914 0.3735280558068819
0.3641166998107194 0.36798032602765307
0.33780570817721034 0.3534749059923812
0.048784033229825496 0.04257697229062324
0.18837858571568433 0.16157502181398226
0.06421609571355047 0.06

-0.08080199632763146 -0.09596331938040364
-0.3618938739056159 -0.37490586872876835
0.2050857921366407 0.20428136075005443
0.2043806407814937 0.19771639618497389
0.27518329735732494 0.29138262519476466
-0.2878775872030116 -0.2955906517384783
0.32205800080731434 0.3224985862645346
-0.05061364530740553 -0.06816884401359558
-0.16032978754313099 -0.13340418175964058
-0.17763739508554016 -0.17428636339197306
-0.2310018378317425 -0.2278669948686705
0.5104530956768825 0.4869348897394964
-0.11664278482404516 -0.11300292556157399
-0.35737628794178805 -0.35332200713025913
0.10852797184306578 0.11370625806543283
-0.11704404626553228 -0.12639564442424667
-0.06224955497316054 -0.06859557594592902
-0.21143386642892137 -0.18767851078814357
-0.3014372419853732 -0.29612230483131213
-0.057815786217476905 -0.07692680443566113
-0.49134931880332966 -0.48142290048029246
0.19867760241914834 0.2031157898880498
0.1529280865998719 0.16242648333475312
-0.5181578028586957 -0.5289978770441081
0.5264928578411441 0.5

0.20899939630827558 0.23146101083354198
-0.2666499458437265 -0.2665782320083435
-0.4602547783735569 -0.4463845340996663
0.30992746319569564 0.3419333877115932
0.32570715177126164 0.3366890861561709
0.2602672076397586 0.24974569090006654
0.41107687950298766 0.41798839862214887
-0.19284807402404408 -0.20964277271041376
0.2478957628581978 0.2278353429327475
-0.05237861267640764 -0.06985485034660177
0.332594231350323 0.3583392236966519
0.12583194405151132 0.08270206878915609
-0.19942163610344038 -0.23069370828345503
-0.34830516673718925 -0.34950673294640844
-0.2469559181804154 -0.22146758699153019
0.1688179006735483 0.17487657767551312
0.0018591989187238256 -0.014335206889361352
-0.18839291254200585 -0.1839211352786141
0.1985801299953569 0.21083863223730287
-0.303673752253621 -0.3176162237359661
0.2384493901225092 0.20430403872344194
0.1739099478690589 0.17092010263376267
0.3608305807674672 0.3755706250980503
0.16705783924008022 0.14089234574111165
-0.1400737064698534 -0.14145812148489711
